import { StyleSheet } from 'react-native'
import { palette } from './theme'

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.canvas,
  },
  appShell: {
    flex: 1,
    backgroundColor: palette.canvas,
  },
  topBar: {
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  brandBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  brandIcon: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: palette.greenSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandText: {
    flex: 1,
  },
  headerControls: {
    alignItems: 'flex-end',
    gap: 8,
  },
  brandEyebrow: {
    color: palette.subtle,
    fontSize: 12,
    marginBottom: 2,
  },
  brandTitle: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 20,
  },
  modeSwitch: {
    alignItems: 'center',
    gap: 6,
  },
  languageToggle: {
    alignItems: 'center',
    gap: 6,
  },
  modeLabel: {
    color: palette.subtle,
    fontSize: 11,
  },
  segmentedSmall: {
    flexDirection: 'row',
    backgroundColor: palette.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.line,
    padding: 3,
    gap: 4,
  },
  segmentMini: {
    minHeight: 28,
    minWidth: 38,
    paddingHorizontal: 10,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentMiniActive: {
    backgroundColor: palette.green,
  },
  segmentMiniText: {
    color: palette.ink,
    fontSize: 11,
    fontWeight: '700',
  },
  segmentMiniTextActive: {
    color: palette.white,
  },
  syncBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 18,
    paddingBottom: 10,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingBottom: 24,
    gap: 14,
  },
  sectionCard: {
    backgroundColor: palette.card,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: palette.line,
    gap: 14,
  },
  sectionHeader: {
    gap: 4,
  },
  sectionTitle: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: '700',
  },
  sectionSubtitle: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  heroCard: {
    borderRadius: 16,
    padding: 16,
    backgroundColor: palette.cardAlt,
    gap: 10,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: palette.white,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  heroBadgeText: {
    color: palette.green,
    fontWeight: '600',
    fontSize: 12,
  },
  heroTitle: {
    color: palette.ink,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 28,
  },
  heroText: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  primaryAction: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: palette.green,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  primaryActionText: {
    color: palette.white,
    fontWeight: '700',
  },
  secondaryAction: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.line,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  secondaryActionText: {
    color: palette.ink,
    fontWeight: '600',
  },
  metricRow: {
    gap: 12,
    paddingRight: 6,
  },
  metricCard: {
    width: 168,
    padding: 14,
    backgroundColor: palette.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.line,
    gap: 8,
  },
  metricIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricIconGreen: {
    backgroundColor: palette.greenSoft,
  },
  metricIconAmber: {
    backgroundColor: palette.amberSoft,
  },
  metricIconRed: {
    backgroundColor: palette.redSoft,
  },
  metricIconBlue: {
    backgroundColor: palette.blueSoft,
  },
  metricLabel: {
    color: palette.subtle,
    fontSize: 12,
  },
  metricValue: {
    color: palette.ink,
    fontSize: 22,
    fontWeight: '800',
  },
  metricDetail: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  calendarDayCard: {
    width: 96,
    padding: 12,
    borderRadius: 16,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.line,
    gap: 4,
  },
  calendarDayCardActive: {
    backgroundColor: palette.green,
    borderColor: palette.green,
  },
  calendarDayShort: {
    color: palette.subtle,
    fontSize: 12,
    fontWeight: '700',
  },
  calendarDayShortActive: {
    color: '#d8efe8',
  },
  calendarDayDate: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: '800',
  },
  calendarDayDateActive: {
    color: palette.white,
  },
  calendarDayMeta: {
    color: palette.muted,
    fontSize: 11,
  },
  calendarDayMetaActive: {
    color: '#d8efe8',
  },
  agendaSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  quickTile: {
    width: '48%',
    minWidth: 148,
    borderRadius: 16,
    padding: 14,
    backgroundColor: palette.cardAlt,
    gap: 6,
  },
  quickTitle: {
    color: palette.ink,
    fontWeight: '700',
    fontSize: 14,
  },
  quickText: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  listCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.line,
    padding: 14,
    gap: 10,
    backgroundColor: palette.card,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  listHeaderMain: {
    flex: 1,
    gap: 2,
  },
  listTitle: {
    color: palette.ink,
    fontWeight: '700',
    fontSize: 15,
  },
  listSubtitle: {
    color: palette.subtle,
    fontSize: 12,
    lineHeight: 16,
  },
  progressTrack: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    backgroundColor: '#e6e2d7',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: palette.green,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  infoLabel: {
    color: palette.subtle,
    fontSize: 12,
    flexShrink: 0,
  },
  infoValue: {
    color: palette.ink,
    fontSize: 13,
    lineHeight: 18,
    flex: 1,
    textAlign: 'right',
  },
  footnote: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  filterRow: {
    gap: 8,
    paddingRight: 6,
  },
  filterChip: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterChipActive: {
    backgroundColor: palette.green,
    borderColor: palette.green,
  },
  filterChipText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: palette.white,
  },
  jobCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.line,
    padding: 14,
    gap: 10,
    backgroundColor: palette.card,
  },
  jobCardActive: {
    borderColor: '#8eb2a7',
    backgroundColor: '#f8fcfa',
  },
  pill: {
    minHeight: 28,
    paddingHorizontal: 10,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pillText: {
    color: palette.ink,
    fontSize: 11,
    fontWeight: '700',
  },
  pillGreen: {
    backgroundColor: palette.greenSoft,
  },
  pillAmber: {
    backgroundColor: palette.amberSoft,
  },
  pillRed: {
    backgroundColor: palette.redSoft,
  },
  pillBlue: {
    backgroundColor: palette.blueSoft,
  },
  pillNeutral: {
    backgroundColor: '#ebe7dc',
  },
  photoStatRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  photoMini: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    minHeight: 28,
    borderRadius: 999,
    backgroundColor: palette.cardAlt,
  },
  photoMiniText: {
    color: palette.muted,
    fontSize: 12,
  },
  expandedArea: {
    gap: 12,
    paddingTop: 2,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  smallAction: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  smallActionText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: '600',
  },
  subsectionLabel: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: '700',
  },
  checklistWrap: {
    gap: 8,
  },
  checkItem: {
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  checkItemActive: {
    backgroundColor: palette.greenSoft,
    borderColor: '#9bc1b4',
  },
  checkItemText: {
    color: palette.ink,
    fontSize: 13,
    flex: 1,
  },
  checkItemTextActive: {
    fontWeight: '700',
  },
  photoActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  photoAction: {
    flex: 1,
    minHeight: 84,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.cardAlt,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 10,
  },
  photoActionTitle: {
    color: palette.ink,
    fontWeight: '700',
    fontSize: 13,
  },
  photoActionCount: {
    color: palette.muted,
    fontSize: 12,
  },
  noteCard: {
    borderRadius: 14,
    backgroundColor: palette.cardAlt,
    padding: 12,
    gap: 6,
  },
  noteTitle: {
    color: palette.ink,
    fontWeight: '700',
    fontSize: 12,
  },
  noteText: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  noteFoot: {
    color: palette.subtle,
    fontSize: 12,
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    color: palette.subtle,
    fontSize: 12,
    fontWeight: '600',
  },
  textInput: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    paddingHorizontal: 14,
    color: palette.ink,
    fontSize: 14,
  },
  multilineInput: {
    minHeight: 110,
    paddingTop: 12,
    paddingBottom: 12,
  },
  optionWrap: {
    gap: 10,
  },
  optionCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    padding: 14,
    gap: 4,
  },
  optionCardActive: {
    backgroundColor: palette.green,
    borderColor: palette.green,
  },
  optionTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  optionTitleActive: {
    color: palette.white,
  },
  optionDetail: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  optionDetailActive: {
    color: '#dcede7',
  },
  stepperCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.cardAlt,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  stepperValue: {
    color: palette.ink,
    fontSize: 24,
    fontWeight: '800',
    marginTop: 4,
  },
  stepperControls: {
    flexDirection: 'row',
    gap: 10,
  },
  stepperButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentedRow: {
    flexDirection: 'row',
    gap: 8,
  },
  segmentButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentButtonActive: {
    backgroundColor: palette.green,
    borderColor: palette.green,
  },
  segmentButtonText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: '700',
  },
  segmentButtonTextActive: {
    color: palette.white,
  },
  extraRow: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'center',
  },
  extraRowActive: {
    backgroundColor: palette.greenSoft,
    borderColor: '#9cc1b3',
  },
  extraMain: {
    flex: 1,
    gap: 3,
  },
  extraTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  extraDetail: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  extraAside: {
    alignItems: 'flex-end',
    gap: 6,
  },
  extraPrice: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: '700',
  },
  switchRow: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.cardAlt,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 14,
    alignItems: 'center',
  },
  switchTextWrap: {
    flex: 1,
    gap: 3,
  },
  switchTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  switchDetail: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  quoteSummary: {
    borderRadius: 16,
    backgroundColor: palette.cardAlt,
    padding: 16,
    gap: 10,
  },
  quoteSummaryLabel: {
    color: palette.subtle,
    fontSize: 12,
  },
  quoteSummaryValue: {
    color: palette.ink,
    fontSize: 30,
    fontWeight: '800',
  },
  quoteSummaryDetail: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  messageCard: {
    borderRadius: 14,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.line,
    padding: 12,
    gap: 6,
  },
  messageCardTitle: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: '700',
  },
  messageCardText: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  pipelineCard: {
    width: 144,
    padding: 14,
    borderRadius: 16,
    backgroundColor: palette.cardAlt,
    gap: 6,
  },
  pipelineLabel: {
    color: palette.subtle,
    fontSize: 12,
  },
  pipelineValue: {
    color: palette.ink,
    fontSize: 26,
    fontWeight: '800',
  },
  pipelineAmount: {
    color: palette.muted,
    fontSize: 12,
  },
  crmService: {
    color: palette.ink,
    fontSize: 14,
    lineHeight: 19,
  },
  collectionTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  collectionTotal: {
    color: palette.ink,
    fontSize: 28,
    fontWeight: '800',
    marginTop: 4,
  },
  switchInline: {
    alignItems: 'center',
    gap: 6,
  },
  switchInlineText: {
    color: palette.subtle,
    fontSize: 12,
  },
  switchRowCompact: {
    borderRadius: 12,
    backgroundColor: palette.cardAlt,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  collectionAmount: {
    color: palette.ink,
    fontSize: 22,
    fontWeight: '800',
  },
  emptyState: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.line,
    borderStyle: 'dashed',
    padding: 18,
    gap: 8,
    alignItems: 'center',
    backgroundColor: palette.cardAlt,
  },
  emptyStateTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  emptyStateText: {
    color: palette.muted,
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 17,
  },
  tabBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 6,
    paddingTop: 8,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: palette.line,
    backgroundColor: '#f8f6f0',
  },
  tabButton: {
    alignItems: 'center',
    gap: 4,
    minWidth: 52,
  },
  tabIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIconWrapActive: {
    backgroundColor: palette.greenSoft,
  },
  tabLabel: {
    color: palette.subtle,
    fontSize: 10,
    fontWeight: '600',
  },
  tabLabelActive: {
    color: palette.green,
  },
})

export default styles
