export const palette = {
  canvas: '#f4f2eb',
  card: '#fbfaf6',
  cardAlt: '#f3efe3',
  ink: '#17211b',
  muted: '#566257',
  subtle: '#738171',
  line: '#ddd8cb',
  green: '#195847',
  greenSoft: '#d9ece6',
  amber: '#9a5c0f',
  amberSoft: '#f3e2cb',
  red: '#a54034',
  redSoft: '#f5dbd8',
  blue: '#3c6e84',
  blueSoft: '#dbeaf0',
  white: '#ffffff',
  black: '#0e1512',
}

export const theme = {
  background: palette.canvas,
  surface: palette.card,
  text: palette.ink,
  textMuted: palette.muted,
  textSubtle: palette.subtle,
  border: palette.line,
  green: palette.green,
  greenLight: palette.greenSoft,
  amber: palette.amber,
  amberLight: palette.amberSoft,
  red: palette.red,
  redLight: palette.redSoft,
  blue: palette.blue,
  blueLight: palette.blueSoft,
}
